
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

package analizadores;

import java.util.LinkedList;
import java_cup.runtime.*;
import tarea45.*;
import java_cup.runtime.XMLElement;

/** CUP v0.11b 20160615 (GIT 4ac7450) generated parser.
  */
@SuppressWarnings({"rawtypes"})
public class Parser1 extends java_cup.runtime.lr_parser {

 public final Class getSymbolContainer() {
    return Simbolos1.class;
}

  /** Default constructor. */
  @Deprecated
  public Parser1() {super();}

  /** Constructor which sets the default scanner. */
  @Deprecated
  public Parser1(java_cup.runtime.Scanner s) {super(s);}

  /** Constructor which sets the default scanner. */
  public Parser1(java_cup.runtime.Scanner s, java_cup.runtime.SymbolFactory sf) {super(s,sf);}

  /** Production table. */
  protected static final short _production_table[][] = 
    unpackFromStrings(new String[] {
    "\000\006\000\002\002\004\000\002\002\003\000\002\003" +
    "\005\000\002\003\005\000\002\003\003\000\002\003\003" +
    "" });

  /** Access to production table. */
  public short[][] production_table() {return _production_table;}

  /** Parse-action table. */
  protected static final short[][] _action_table = 
    unpackFromStrings(new String[] {
    "\000\011\000\006\005\006\006\004\001\002\000\006\002" +
    "\ufffc\004\ufffc\001\002\000\004\002\013\001\002\000\006" +
    "\002\ufffd\004\ufffd\001\002\000\006\002\000\004\010\001" +
    "\002\000\006\005\012\006\011\001\002\000\006\002\ufffe" +
    "\004\ufffe\001\002\000\006\002\uffff\004\uffff\001\002\000" +
    "\004\002\001\001\002" });

  /** Access to parse-action table. */
  public short[][] action_table() {return _action_table;}

  /** <code>reduce_goto</code> table. */
  protected static final short[][] _reduce_table = 
    unpackFromStrings(new String[] {
    "\000\011\000\006\002\004\003\006\001\001\000\002\001" +
    "\001\000\002\001\001\000\002\001\001\000\002\001\001" +
    "\000\002\001\001\000\002\001\001\000\002\001\001\000" +
    "\002\001\001" });

  /** Access to <code>reduce_goto</code> table. */
  public short[][] reduce_table() {return _reduce_table;}

  /** Instance of action encapsulation class. */
  protected CUP$Parser1$actions action_obj;

  /** Action encapsulation object initializer. */
  protected void init_actions()
    {
      action_obj = new CUP$Parser1$actions(this);
    }

  /** Invoke a user supplied parse action. */
  public java_cup.runtime.Symbol do_action(
    int                        act_num,
    java_cup.runtime.lr_parser parser,
    java.util.Stack            stack,
    int                        top)
    throws java.lang.Exception
  {
    /* call code in generated class */
    return action_obj.CUP$Parser1$do_action(act_num, parser, stack, top);
  }

  /** Indicates start state. */
  public int start_state() {return 0;}
  /** Indicates start production. */
  public int start_production() {return 0;}

  /** <code>EOF</code> Symbol index. */
  public int EOF_sym() {return 0;}

  /** <code>error</code> Symbol index. */
  public int error_sym() {return 1;}



    public Nodo1 raiz;

    /**
    * Metodo para error sintactico
    **/
    public void syntax_error(Symbol s){
        System.err.println("Error sintacto línea " + (s.left+1) +" columna "+(s.right+1)+ ". No se esperaba " +s.value+"."); 
            tarea45.main.listaSintacticos.add(new ErrorLexico(String.valueOf(s.value), "Sintactico", Integer.toString(s.left +1), Integer.toString(s.right+1)));
        }
    
    public void unrecovered_syntax_error(Symbol s) throws java.lang.Exception{
        System.err.println("Error irrecuperable en la linea " + (s.left)+ " columna " +s.right+". Elemento " + s.value + " no reconocido.");
        
    }



/** Cup generated class to encapsulate user supplied action code.*/
@SuppressWarnings({"rawtypes", "unchecked", "unused"})
class CUP$Parser1$actions {
  private final Parser1 parser;

  /** Constructor */
  CUP$Parser1$actions(Parser1 parser) {
    this.parser = parser;
  }

  /** Method 0 with the actual generated action code for actions 0 to 300. */
  public final java_cup.runtime.Symbol CUP$Parser1$do_action_part00000000(
    int                        CUP$Parser1$act_num,
    java_cup.runtime.lr_parser CUP$Parser1$parser,
    java.util.Stack            CUP$Parser1$stack,
    int                        CUP$Parser1$top)
    throws java.lang.Exception
    {
      /* Symbol object for return from actions */
      java_cup.runtime.Symbol CUP$Parser1$result;

      /* select the action based on the action number */
      switch (CUP$Parser1$act_num)
        {
          /*. . . . . . . . . . . . . . . . . . . .*/
          case 0: // $START ::= S EOF 
            {
              Object RESULT =null;
		int start_valleft = ((java_cup.runtime.Symbol)CUP$Parser1$stack.elementAt(CUP$Parser1$top-1)).left;
		int start_valright = ((java_cup.runtime.Symbol)CUP$Parser1$stack.elementAt(CUP$Parser1$top-1)).right;
		Nodo1 start_val = (Nodo1)((java_cup.runtime.Symbol) CUP$Parser1$stack.elementAt(CUP$Parser1$top-1)).value;
		RESULT = start_val;
              CUP$Parser1$result = parser.getSymbolFactory().newSymbol("$START",0, ((java_cup.runtime.Symbol)CUP$Parser1$stack.elementAt(CUP$Parser1$top-1)), ((java_cup.runtime.Symbol)CUP$Parser1$stack.peek()), RESULT);
            }
          /* ACCEPT */
          CUP$Parser1$parser.done_parsing();
          return CUP$Parser1$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 1: // S ::= LISTA 
            {
              Nodo1 RESULT =null;
		int lleft = ((java_cup.runtime.Symbol)CUP$Parser1$stack.peek()).left;
		int lright = ((java_cup.runtime.Symbol)CUP$Parser1$stack.peek()).right;
		Nodo1 l = (Nodo1)((java_cup.runtime.Symbol) CUP$Parser1$stack.peek()).value;
		raiz = l;
              CUP$Parser1$result = parser.getSymbolFactory().newSymbol("S",0, ((java_cup.runtime.Symbol)CUP$Parser1$stack.peek()), ((java_cup.runtime.Symbol)CUP$Parser1$stack.peek()), RESULT);
            }
          return CUP$Parser1$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 2: // LISTA ::= LISTA coma par 
            {
              Nodo1 RESULT =null;
		int lleft = ((java_cup.runtime.Symbol)CUP$Parser1$stack.elementAt(CUP$Parser1$top-2)).left;
		int lright = ((java_cup.runtime.Symbol)CUP$Parser1$stack.elementAt(CUP$Parser1$top-2)).right;
		Nodo1 l = (Nodo1)((java_cup.runtime.Symbol) CUP$Parser1$stack.elementAt(CUP$Parser1$top-2)).value;
		int pleft = ((java_cup.runtime.Symbol)CUP$Parser1$stack.peek()).left;
		int pright = ((java_cup.runtime.Symbol)CUP$Parser1$stack.peek()).right;
		String p = (String)((java_cup.runtime.Symbol) CUP$Parser1$stack.peek()).value;
		
                    l.valor += Integer.parseInt(p);
                    if(l.paridad){
                        l.paridad = true;
                    }else{
                        l.paridad = false;
                    }
                    RESULT = l;
                
              CUP$Parser1$result = parser.getSymbolFactory().newSymbol("LISTA",1, ((java_cup.runtime.Symbol)CUP$Parser1$stack.elementAt(CUP$Parser1$top-2)), ((java_cup.runtime.Symbol)CUP$Parser1$stack.peek()), RESULT);
            }
          return CUP$Parser1$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 3: // LISTA ::= LISTA coma impar 
            {
              Nodo1 RESULT =null;
		int lleft = ((java_cup.runtime.Symbol)CUP$Parser1$stack.elementAt(CUP$Parser1$top-2)).left;
		int lright = ((java_cup.runtime.Symbol)CUP$Parser1$stack.elementAt(CUP$Parser1$top-2)).right;
		Nodo1 l = (Nodo1)((java_cup.runtime.Symbol) CUP$Parser1$stack.elementAt(CUP$Parser1$top-2)).value;
		int pleft = ((java_cup.runtime.Symbol)CUP$Parser1$stack.peek()).left;
		int pright = ((java_cup.runtime.Symbol)CUP$Parser1$stack.peek()).right;
		String p = (String)((java_cup.runtime.Symbol) CUP$Parser1$stack.peek()).value;
		
                    l.valor += Integer.parseInt(p);
                    if(l.paridad){
                        l.paridad = false;
                    }else{
                        l.paridad = true;
                    }
                    RESULT = l;
                
              CUP$Parser1$result = parser.getSymbolFactory().newSymbol("LISTA",1, ((java_cup.runtime.Symbol)CUP$Parser1$stack.elementAt(CUP$Parser1$top-2)), ((java_cup.runtime.Symbol)CUP$Parser1$stack.peek()), RESULT);
            }
          return CUP$Parser1$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 4: // LISTA ::= par 
            {
              Nodo1 RESULT =null;
		int pleft = ((java_cup.runtime.Symbol)CUP$Parser1$stack.peek()).left;
		int pright = ((java_cup.runtime.Symbol)CUP$Parser1$stack.peek()).right;
		String p = (String)((java_cup.runtime.Symbol) CUP$Parser1$stack.peek()).value;
		RESULT = new Nodo1(true, Integer.parseInt(p));
              CUP$Parser1$result = parser.getSymbolFactory().newSymbol("LISTA",1, ((java_cup.runtime.Symbol)CUP$Parser1$stack.peek()), ((java_cup.runtime.Symbol)CUP$Parser1$stack.peek()), RESULT);
            }
          return CUP$Parser1$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 5: // LISTA ::= impar 
            {
              Nodo1 RESULT =null;
		int pleft = ((java_cup.runtime.Symbol)CUP$Parser1$stack.peek()).left;
		int pright = ((java_cup.runtime.Symbol)CUP$Parser1$stack.peek()).right;
		String p = (String)((java_cup.runtime.Symbol) CUP$Parser1$stack.peek()).value;
		RESULT = new Nodo1(false, Integer.parseInt(p));
              CUP$Parser1$result = parser.getSymbolFactory().newSymbol("LISTA",1, ((java_cup.runtime.Symbol)CUP$Parser1$stack.peek()), ((java_cup.runtime.Symbol)CUP$Parser1$stack.peek()), RESULT);
            }
          return CUP$Parser1$result;

          /* . . . . . .*/
          default:
            throw new Exception(
               "Invalid action number "+CUP$Parser1$act_num+"found in internal parse table");

        }
    } /* end of method */

  /** Method splitting the generated action code into several parts. */
  public final java_cup.runtime.Symbol CUP$Parser1$do_action(
    int                        CUP$Parser1$act_num,
    java_cup.runtime.lr_parser CUP$Parser1$parser,
    java.util.Stack            CUP$Parser1$stack,
    int                        CUP$Parser1$top)
    throws java.lang.Exception
    {
              return CUP$Parser1$do_action_part00000000(
                               CUP$Parser1$act_num,
                               CUP$Parser1$parser,
                               CUP$Parser1$stack,
                               CUP$Parser1$top);
    }
}

}
