
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

package analizadores;

/** CUP generated class containing symbol constants. */
public class Simbolos1 {
  /* terminals */
  public static final int impar = 4;
  public static final int error = 1;
  public static final int par = 3;
  public static final int coma = 2;
  public static final int EOF = 0;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "coma",
  "par",
  "impar"
  };
}

