/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package tarea45;

import analizadores.*;
import java.io.File;
import java.io.StringReader;

/**
 *
 * @author Junior
 */
public class Form extends javax.swing.JFrame {

    /**
     * Creates new form Form
     */
    public Form() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        txtEntrada = new javax.swing.JTextArea();
        jScrollPane2 = new javax.swing.JScrollPane();
        txtResultado = new javax.swing.JTextArea();
        btnEjercicio1 = new javax.swing.JButton();
        btnEjercico2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        txtEntrada.setColumns(20);
        txtEntrada.setRows(5);
        jScrollPane1.setViewportView(txtEntrada);

        txtResultado.setEditable(false);
        txtResultado.setColumns(20);
        txtResultado.setRows(5);
        jScrollPane2.setViewportView(txtResultado);

        btnEjercicio1.setText("Ejercicio1");
        btnEjercicio1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnEjercicio1MouseClicked(evt);
            }
        });

        btnEjercico2.setText("Ejercicio2");
        btnEjercico2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnEjercico2MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 380, Short.MAX_VALUE)
                    .addComponent(jScrollPane2)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(btnEjercicio1)
                        .addGap(16, 16, 16)
                        .addComponent(btnEjercico2)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 11, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnEjercicio1)
                    .addComponent(btnEjercico2))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnEjercicio1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnEjercicio1MouseClicked
        try{
            Nodo1 nodo = new Nodo1();
            txtResultado.setText("");
            StringReader read = new StringReader(txtEntrada.getText());
            Lexico1 lexico = new Lexico1(read);
            Parser1 sintactico = new Parser1(lexico);
            sintactico.parse();
            String imprimir = "";
            imprimir += "Consola:\n";
            nodo = sintactico.raiz;
            if(nodo.paridad){
                imprimir += nodo.valor + " es par";
            }else{
                imprimir += nodo.valor + " es impar";
            }
            
            if(!main.listaErrores.isEmpty()){
                imprimir += "Erroreres Léxicos:\n";
                for(ErrorLexico e: main.listaErrores){
                    System.out.println(e.err);
                    imprimir += e.err + " " + e.tipo + " " + e.fila + " " + e.columna+"\n";
                }
            }
            
            if(!main.listaSintacticos.isEmpty()){
                imprimir += "Erroreres Sintácticos:\n";
                for(ErrorLexico e: main.listaSintacticos){
                    System.out.println(e.err);
                    imprimir += e.err + " " + e.tipo + " " + e.fila + " " + e.columna+"\n";
                }
            }
            txtResultado.setText(imprimir);
        }catch(Exception e){
            System.out.println(e);
        }
    }//GEN-LAST:event_btnEjercicio1MouseClicked

    private void btnEjercico2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnEjercico2MouseClicked
        try{
            Nodo2 nodo = new Nodo2();
            txtResultado.setText("");
            StringReader read = new StringReader(txtEntrada.getText());
            Lexico1 lexico = new Lexico1(read);
            Parser2 sintactico = new Parser2(lexico);
            sintactico.parse();
            String imprimir = "";
            imprimir += "Consola:\n";
            nodo = sintactico.raiz;
            imprimir += "Suma de los pares = " + nodo.pares +"\nMultiplicacion de los impares = " + nodo.impares
                    +"\nCantidad de pares = " + nodo.contadorPar +"\nCantidad de impares = " + nodo.contadorImpar;
            
            if(!main.listaErrores.isEmpty()){
                imprimir += "Erroreres Léxicos:\n";
                for(ErrorLexico e: main.listaErrores){
                    System.out.println(e.err);
                    imprimir += e.err + " " + e.tipo + " " + e.fila + " " + e.columna+"\n";
                }
            }
            
            if(!main.listaSintacticos.isEmpty()){
                imprimir += "Erroreres Sintácticos:\n";
                for(ErrorLexico e: main.listaSintacticos){
                    System.out.println(e.err);
                    imprimir += e.err + " " + e.tipo + " " + e.fila + " " + e.columna+"\n";
                }
            }
            txtResultado.setText(imprimir);
        }catch(Exception e){
            System.out.println(e);
        }
    }//GEN-LAST:event_btnEjercico2MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Form.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Form.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Form.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Form.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Form().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnEjercicio1;
    private javax.swing.JButton btnEjercico2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextArea txtEntrada;
    private javax.swing.JTextArea txtResultado;
    // End of variables declaration//GEN-END:variables
}
